### ISSUE TITLE
Reloading extension not necessary in most cases

### ISSUE THREAD

**Issue by lreinink** [larscom/angular-chrome-extension#5]
First of all, thanks for creating this wonderful project. It has really helped me.

Could you please explain how it's possible that reloading is not necessary in most cases, except when changing background pages or content pages?

**Comment by larscom** [comment]
Hi, its because the content script and background script gets loaded once (when you load the extension)

And the Angular scripts gets loaded every time you startup the popup.

So this means when you close the popup and make some changes to the angular code and start the popup again, it has the newly build code.
